# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  adminapi:
    image: adminapi
    build:
      context: ./AdminApi
      dockerfile: ./Dockerfile
    ports:
      - 50200:50200
  admindb:
    image: admindb
    build:
      context: ./AdminDb
      dockerfile: ./Dockerfile
    ports:
      - 7432:5432
    environment:
      - POSTGRES_PASSWORD=topsecret
  rabbit:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
  eventapi:
    image: eventapi
    build:
      context: ./EventApi
      dockerfile: ./Dockerfile
    ports:
      - 50201:50201
